<a href="https://colab.research.google.com/github/AkilaliBeig/AI_Machine_Learning/blob/main/NLP/Text%20Data/NLP_IMDB_Text_preprocess%26_representtion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.
Path to dataset files: /kaggle/input/imdb-dataset-of-50k-movie-reviews

In [2]:

import pandas as pd
df = pd.read_csv('/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [5]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [6]:
df.count()

review       50000
sentiment    50000
dtype: int64

In [8]:
# run in terminal / colab cell if needed
!pip install spacy contractions emoji
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.7)
Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.19.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.11.10)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.5.0)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.12/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.10.5)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.3.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (1.17.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 12.1 MB/s eta 0:00:00
Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Downloading anyascii-0.3.3-py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 13.5 MB/s eta 0:00:00
Downloading pyahocorasick-2.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 8.7 MB/s eta 0:00:00
Installing collected packages: pyahocorasick, emoji, anyascii, textsearch, contractions
Successfully installed anyascii-0.3.3 contractions-0.1.73 emoji-2.15.0 pyahocorasick-2.2.0 textsearch-0.0.24
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 100.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [7]:
import re
import string
import pandas as pd

# optional libraries
try:
    import spacy
    nlp = spacy.load("en_core_web_sm", disable=["ner"])  # faster: disable NER if not needed
except Exception:
    nlp = None

try:
    import contractions            # for expanding "don't" -> "do not"
except Exception:
    contractions = None

try:
    import emoji                  # for demojize
except Exception:
    emoji = None

**Text Preprocessing**

Lowercasing

In [9]:
df['review'].dtype

dtype('O')

In [10]:
df['review'] = df['review'].astype(str)

In [11]:
df['review'] = df['review'].str.lower()

In [12]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

Remove HTML tags

In [13]:
html_re = re.compile(r'<.*?>')
df['review'] = df['review'].apply(lambda x: re.sub(html_re, ' ', x))

In [14]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.  this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.  ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.  3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

Remove URLs

In [15]:
url_re = re.compile(r'http\S+|www\.\S+')
df['review'] = df['review'].apply(lambda x: re.sub(url_re, ' ', x))

In [16]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.  this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.  ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.  3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

Emoji handling (remove or convert)

In [17]:
pip install emoji

Requirement already satisfied: emoji in /usr/local/lib/python3.12/dist-packages (2.15.0)

In [18]:
if emoji:
    df['review'] = df['review'].apply(lambda x: emoji.demojize(x))  # converts 😍 -> :smiling_face_with_heart_eyes:

In [19]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.  this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.  ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.  3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

Expand contractions

In [18]:
def expand_contractions(text):
    if contractions:
        return contractions.fix(text)
    else:
        return text


df['review'] = df['review'].apply(expand_contractions)

In [19]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.  this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.  ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.  3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

Chat / slang replacement

In [20]:
chat_map = {
    "u": "you",
    "ur": "your",
    "btw": "by the way",
    "omg": "oh my god",
    "idk": "i do not know",
    "thx": "thanks",
    "pls": "please",
    "gr8": "great",
}


# Function to replace chat words
def chat_word_treatment(text):
  if not isinstance(text, str):   # if text is None or not string
        return ""                   # return empty string
  words = text.split()
  new_words = []
  for word in words:
    # replace if word exists in map, else keep as is
    new_words.append(chat_map.get(word.lower(), word))
  return " ".join(new_words)



# Apply on overview column
df['review'] = df['review'].apply(chat_word_treatment)

In [21]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time. this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie. ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots. 3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

Remove URLs, punctuation & special character

In [22]:
# remove punctuation (keeping whitespace)
table = str.maketrans('', '', string.punctuation)
df['review'] = df['review'].apply(lambda x: x.translate(table))
# remove extra non-alphanumeric chars (if needed)
df['review'] = df['review'].apply(lambda x: re.sub(r'[^0-9a-zA-Z\s]', ' ', x))
# collapse multiple spaces
df['review'] = df['review'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())

In [23]:
df['review'][3]

'basically theres a family where a little boy jake thinks theres a zombie in his closet his parents are fighting all the time this movie is slower than a soap opera and suddenly jake decides to become rambo and kill the zombie ok first of all when youre going to make a film you must decide if its a thriller or a drama as a drama the movie is watchable parents are divorcing arguing like in real life and then we have jake with his closet which totally ruins all the film i expected to see a boogeyman similar movie and instead i watched a drama with some meaningless thriller spots 3 out of 10 just for the well playing parents descent dialogs as for the shots with jake just ignore them'

Remove stopwords (but keep negations)

In [24]:
from spacy.lang.en.stop_words import STOP_WORDS
import spacy

# Load spacy English model
nlp = spacy.load("en_core_web_sm")

# 1. Load SpaCy’s default stopwords
stop_words = spacy.lang.en.stop_words.STOP_WORDS

# 2. Keep important negations (because they change sentiment)
for w in ["no", "not", "never", "none", "n't"]:
    stop_words.discard(w)

# 3. Function to remove stopwords
def remove_stop_spacy(doc_text):
    doc = nlp(doc_text)  # tokenize using SpaCy
    tokens = [token.text for token in doc
              if token.text.lower() not in stop_words and not token.is_space]
    return " ".join(tokens)

# 4. Apply function to reviews column
df['review'] = df['review'].apply(remove_stop_spacy)

In [25]:
df['review'][3]

'basically s family little boy jake thinks s zombie closet parents fighting time movie slower soap opera suddenly jake decides rambo kill zombie ok going film decide thriller drama drama movie watchable parents divorcing arguing like real life jake closet totally ruins film expected boogeyman similar movie instead watched drama meaningless thriller spots 3 10 playing parents descent dialogs shots jake ignore'

✅ Step-by-step

Stopwords → Words like the, is, at, on, of, for that don’t carry much meaning in NLP are removed.
Example: "The movie is very good" → "movie good"

Why discard(w)?
Normally, SpaCy includes words like not, no, never in stopwords.
But for sentiment analysis (your IMDB dataset), these words are important!

"I like this movie" vs "I do **not** like this movie" → sentiment changes completely.
That’s why we keep negations.

remove_stop_spacy() function:

nlp(doc_text) → tokenizes text using SpaCy.

Removes stopwords (if token.text.lower() not in stop_words).

Removes spaces.

Joins back into cleaned text.

Apply on DataFrame → Every review is processed, and stopwords (except negations) are removed.

Tokenization

In [26]:
def tokenize_spacy(text):
    return [token.text for token in nlp(text)]
df['tokens'] = df['review'].apply(lambda x: [t.text for t in nlp(x)])

In [27]:
df['tokens'][3]

['basically',
 's',
 'family',
 'little',
 'boy',
 'jake',
 'thinks',
 's',
 'zombie',
 'closet',
 'parents',
 'fighting',
 'time',
 'movie',
 'slower',
 'soap',
 'opera',
 'suddenly',
 'jake',
 'decides',
 'rambo',
 'kill',
 'zombie',
 'ok',
 'going',
 'film',
 'decide',
 'thriller',
 'drama',
 'drama',
 'movie',
 'watchable',
 'parents',
 'divorcing',
 'arguing',
 'like',
 'real',
 'life',
 'jake',
 'closet',
 'totally',
 'ruins',
 'film',
 'expected',
 'boogeyman',
 'similar',
 'movie',
 'instead',
 'watched',
 'drama',
 'meaningless',
 'thriller',
 'spots',
 '3',
 '10',
 'playing',
 'parents',
 'descent',
 'dialogs',
 'shots',
 'jake',
 'ignore']

Lemmatization

In [28]:
    def lemmatize_spacy(text):
        doc = nlp(text)
        lemmas = []
        for token in doc:
            if token.lemma_ == "-PRON-":       # spaCy uses -PRON- for pronouns
                lemmas.append(token.text.lower())
            else:
                lemmas.append(token.lemma_.lower())
        return " ".join(lemmas)
    df['clean_review'] = df['review'].apply(lemmatize_spacy)

In [29]:
df['clean_review'][3]

'basically s family little boy jake think s zombie closet parent fight time movie slow soap opera suddenly jake decide rambo kill zombie ok go film decide thriller drama drama movie watchable parent divorce argue like real life jake closet totally ruin film expect boogeyman similar movie instead watch drama meaningless thriller spot 3 10 play parent descent dialog shot jake ignore'

In [30]:
df['review'][3]

'basically s family little boy jake thinks s zombie closet parents fighting time movie slower soap opera suddenly jake decides rambo kill zombie ok going film decide thriller drama drama movie watchable parents divorcing arguing like real life jake closet totally ruins film expected boogeyman similar movie instead watched drama meaningless thriller spots 3 10 playing parents descent dialogs shots jake ignore'

Spelling

In [ ]:
!pip install autocorrect

In [ ]:
from autocorrect import Speller
spell = Speller(lang='en')
df['clean_review'] = df['clean_review'].apply(lambda x: " ".join([spell(w) for w in x.split()]))

In [32]:
print(df[['review','clean_review']].head(4))

                                              review  \
0  reviewers mentioned watching 1 oz episode ll h...
1  wonderful little production filming technique ...
2  thought wonderful way spend time hot summer we...
3  basically s family little boy jake thinks s zo...

                                        clean_review
0  reviewer mention watch 1 oz episode ll hook ri...
1  wonderful little production filming technique ...
2  think wonderful way spend time hot summer week...
3  basically s family little boy jake think s zom...

In [33]:
df.to_csv("imdb_50k_preprocessed.csv", index=False, encoding="utf-8")

Text Representation

In [4]:
import pandas as pd

df=pd.read_csv("imdb_50k_preprocessed.csv")

In [5]:
df.count()

review          50000
sentiment       50000
tokens          50000
clean_review    50000
dtype: int64

In [6]:
# Find out the number of words in the entire corpus and also the total number of unique words(vocabulary) using just python

In [7]:
# Combine all reviews into one large string (corpus)
all_text = " ".join(df['clean_review'].dropna().astype(str))

df['clean_review'].dropna().astype(str)
→ makes sure we don’t have NaN values.

" ".join(...)
→ merges all reviews into one big text corpus.

In [8]:
# Split into words
all_words = all_text.split()

# Total number of words (tokens)
total_words = len(all_words)

# Unique words (vocabulary size)
unique_words = len(set(all_words))

print("Total words in corpus:", total_words)
print("Total unique words (vocabulary):", unique_words)

Total words in corpus: 5360274
Total unique words (vocabulary): 150096

.split()
→ splits text into words (by whitespace).

len(all_words)
→ total number of word tokens.

len(set(all_words))
→ total number of unique words (vocabulary).

Bag of Words (BoW)

In [9]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder

In [10]:
# Use cleaned text column
texts = df['clean_review'].astype(str).tolist()

# Build CountVectorizer (uni-grams)
cv = CountVectorizer(ngram_range=(1,1), min_df=1)  # min_df can be increased to remove rare words
X_counts = cv.fit_transform(texts)  # sparse matrix: (n_docs, n_features)

In [11]:
X_counts

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4198578 stored elements and shape (50000, 150062)>

In [12]:
# Vocabulary (word -> column index)
vocab = cv.vocabulary_        # dict: word -> index
vocab_size = len(vocab)
print("Vocabulary size (uni-gram):", vocab_size)

Vocabulary size (uni-gram): 150062

In [13]:
# Total occurrences of each word across the whole corpus
word_counts = np.asarray(X_counts.sum(axis=0)).ravel()  # array aligned with cv.get_feature_names_out()
features = cv.get_feature_names_out()
counts_df = pd.DataFrame({'word': features, 'count': word_counts})
counts_df = counts_df.sort_values('count', ascending=False).reset_index(drop=True)

# Show top 20 words
print(counts_df.head(20))

         word   count
0         not  128888
1       movie  100926
2        film   93385
3        like   42948
4        good   38755
5        time   29749
6   character   27964
7       watch   26939
8         bad   24947
9       story   24708
10         no   24479
11        see   23683
12      think   21263
13      scene   21025
14      great   19797
15       look   19090
16       know   18593
17     people   18229
18        end   17819
19        way   16941

In [14]:
counts_df.count()

word     150062
count    150062
dtype: int64

In [15]:
word_counts[30372]

np.int64(1)

In [16]:
features[30372] #word name

'costarhe'

Bag of Bi-gram and Tri-gram (and dimensionality observation)

In [17]:
# Bi-grams
cv_bigram = CountVectorizer(ngram_range=(2,2), min_df=1)
X_bigram = cv_bigram.fit_transform(texts)
vocab_bigram = cv_bigram.get_feature_names_out()
print("Bi-gram vocab size:", len(vocab_bigram))

# Tri-grams
cv_trigram = CountVectorizer(ngram_range=(3,3), min_df=1)
X_trigram = cv_trigram.fit_transform(texts)
vocab_trigram = cv_trigram.get_feature_names_out()
print("Tri-gram vocab size:", len(vocab_trigram))

# Show top 20 bi-grams and their counts
counts_bigram = np.asarray(X_bigram.sum(axis=0)).ravel()
bigram_df = pd.DataFrame({'ngram': vocab_bigram, 'count': counts_bigram}).sort_values('count', ascending=False)
print(bigram_df.head(20))

Bi-gram vocab size: 2675259
Tri-gram vocab size: 4764524
                  ngram  count
1564105       movie not   5755
875741         film not   4391
1640546        not know   4084
1405095       look like   3818
2526203          ve see   3731
2577200     watch movie   3169
189454        bad movie   2718
2613785        will not   2638
1639291        not good   2550
1636029         not bad   2347
1644799       not think   2262
1011289      good movie   2243
2219095  special effect   2232
1640766        not like   2157
2089009       see movie   2124
1563136      movie like   2117
1438441  main character   1909
2573713      waste time   1750
2661836        year old   1709
854250        feel like   1702

In [18]:

# Show top 20 bi-grams and their counts
counts_trigram = np.asarray(X_trigram.sum(axis=0)).ravel()
trigram_df = pd.DataFrame({'ngram': vocab_trigram, 'count': counts_trigram}).sort_values('count', ascending=False)
print(trigram_df.head(20))

                    ngram  count
2768410      movie ve see    637
2984150    not waste time    568
1490757       film ve see    438
309195      bad movie see    353
309331       bad movie ve    261
2851534     new york city    261
2984452   not watch movie    249
4475525      ve never see    225
4477133      ve see movie    223
4704370      world war ii    217
2932731    not good movie    214
1748593  good thing movie    206
4560184  waste time money    205
2514821     make no sense    203
2905423     not bad movie    191
2945015    not like movie    187
333950    base true story    183
2967860     not see movie    180
3725459     see long time    177
2743678    movie not good    175

In [19]:
print(counts_df.count())
print(bigram_df.count())
print(trigram_df.count())

word     150062
count    150062
dtype: int64
ngram    2675259
count    2675259
dtype: int64
ngram    4764524
count    4764524
dtype: int64

TF–IDF

In [20]:
tfidf = TfidfVectorizer(ngram_range=(1,1), min_df=1)  # uni-gram TF-IDF
X_tfidf = tfidf.fit_transform(texts)

# Vocabulary and idf values
features = tfidf.get_feature_names_out()
idf_values = tfidf.idf_   # array aligned with features

idf_df = pd.DataFrame({'word': features, 'idf': idf_values}).sort_values('idf', ascending=False)
print("Vocabulary size (tfidf uni-gram):", len(features))
print(idf_df.head(20))  # top 20 by idf (rare words)

Vocabulary size (tfidf uni-gram): 150062
                                                word        idf
150061  zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz  11.126651
150060     zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz  11.126651
150059               zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz  11.126651
2                                      0000000000001  11.126651
3                                           00000001  11.126651
4                                             000001  11.126651
5                                           00000110  11.126651
6                                               0001  11.126651
7                                              00015  11.126651
150058                            zzzzzzzzzzzzzzzzzz  11.126651
9                                               0010  11.126651
150040                                        zwarts  11.126651
150039                                     zwartboek  11.126651
150037                                   zvyagvatsev  11.126651
150034                                        zvezda  11.126651
150033                                      zuzzzuzz  11.126651
150032                                     zuwarrior  11.126651
150031                                         zuthe  11.126651
150030                                        zutaut  11.126651
150029                                          zurn  11.126651

In [29]:
idf_df.sort_values('idf', ascending=False).reset_index(drop=True)

            word        idf
0       00383042  11.126651
1            006  11.126651
2           0069  11.126651
3           0130  11.126651
4         013007  11.126651
...          ...        ...
150057      good   1.770696
150058      like   1.727510
150059      film   1.530980
150060     movie   1.443156
150061       not   1.197666

[150062 rows x 2 columns]